# Generated by Django 3.2.13 on 2023-05-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_review_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='movies.Tag'),
        ),
    ]
